
services:
  postgres:
    network_mode: host
    image: postgres:18.0-alpine3.22
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/18/docker