services:
    postgres:
        # network_mode: host
        image: postgres:latest
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_USER: default
            POSTGRES_PASSWORD: password
        ports:
            - '5432:5432'
        volumes:
            - ./data/postgres_data:/var/lib/postgresql/data
        # command:
        #     [
        #         '-c',
        #         'shared_buffers=4GB',
        #         '-c',
        #         'work_mem=128MB',
        #         '-c',
        #         'maintenance_work_mem=2GB',
        #         '-c',
        #         'effective_cache_size=12GB',
        #         '-c',
        #         'max_connections=150',
        #         '-c',
        #         'max_worker_processes=8',
        #         '-c',
        #         'max_parallel_workers_per_gather=4',
        #         '-c',
        #         'max_parallel_workers=8',
        #     ]

volumes:
    postgres_data:
