
services:
  postgres:
    network_mode: host
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U default -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: