export const messages = {
  en: {
    components: {
      ErrorBox: {
        title: 'Error',
        message: 'Something went wrong...',
        cta: 'Please refresh',
      },
      WalletConnect: {
        button: 'Connect Wallet',
        cta: 'Connect Wallet',
        ctaAddress: 'Connect Address',
        balance: 'Balance',
        cancel: 'Cancel',
        back: 'Go back',
        disconnect: 'Disconnect Wallet',
        connecting: 'Connecting Wallet',
        wait: 'Please wait...',
        trouble: 'Troubleshooting',
        slow: 'The connection seems to be slow...',
        retry: 'Try again',
        failed: 'Connection Failed',
        failedSub: 'Was not able to connect to your wallet',
        publicAddressDisclaimer:
                    '* Connecting public address doesn\'t connect to your wallet and is used only for CLI command generation.',
        recommendedWallet: 'We recommend connecting with address only',
        otherWallet: 'Make sure you have a wallet browser extension enabled.',
        enterAddress: 'Enter your wallet address',
        addressPlaceholder: 'e.g. atone1ad453f23bc2d...',
        singleClickDisable: 'Single-Click Disable',
        singleClickEnable: 'Single-Click Enable',
      },
      Wallet: {
        popupSign:
                    'Check your wallet extension to sign the transaction, after submitting the transaction please wait a moment.',
        broadcastSuccess: 'Successfully Broadcasted',
      },
      Button: {
        submit: 'Submit',
        close: 'Close',
        showMore: 'Show more',
        copyLink: 'Copy link',
        follow: 'Follow',
        unfollow: 'Unfollow',
        newPost: 'New post',
        reply: 'Reply',
        closeReply: 'Close Reply',
        createReply: 'Create Reply',
        mintscan: 'See on Mintscan',
        pingpub: 'See on Ping.pub',
        showImage: 'Show image',
        hideImage: 'Hide image',
        viewOnExplorer: 'View on explorer',
        tip: 'Tip',
        adjustDefaultAmount: 'Adjust Default Amount',
      },
      InputPhoton: {
        notEnough: 'Not enough balance',
        placeholder: 'Type amount',
        remaining: 'remaining',
      },
      PopupTitles: {
        likePost: 'Like Post',
        dislikePost: 'Dislike Post',
        newPost: 'New Post',
        reply: 'Reply to Post',
        flagPost: 'Flag Post',
        follow: 'Follow User',
        unfollow: 'Unfollow User',
        tipUser: 'Tip User',
        invalidDefaultAmount: 'Not enough balance',
      },
      PopupDescriptions: {
        flagPost: 'Flagging a post allows our moderation team to take a look and hide it if it violates community guidelines.',
        invalidDefaultAmount: 'You have set a Default Amount and you don\'t have enough balance.\nPlease adjust your Default Amount.',
      },
      Tabs: {
        feed: 'Global Feed',
        following: 'Following',
        posts: 'Posts',
        myPosts: 'My Posts',
        replies: 'Replies',
        myReplies: 'My Replies',
      },
      Headings: {
        profile: 'Profile',
        myProfile: 'My Profile',
        notifications: 'Notifications',
        settings: 'Settings',
        manageFollows: 'Manage Following',
        envConfig: 'Environment Config',
        authz: 'Authz',
        post: 'Post',
        explore: 'Explore',
        about: 'About',
      },
      SearchInput: {
        noResults: 'No results found',
        failedToSearch: 'Failed to search',
      },
      Filter: {
        posts: 'Filter posts by PHOTON',
        amount: 'Amount',
      },
      PostsList: {
        empty: 'No Posts Available',
      },
      PostView: {
        invalidDefaultAmount: 'You can\'t reply to this post because you have set a Default Amount and you don\'t have enough balance.\nPlease adjust your Default Amount.',
      },
      RepliesGroupsList: {
        empty: 'No Replies Available',
      },
      Notifications: {
        like: 'Liked your post',
        dislike: 'Disliked your post',
        flag: 'Redflagged your post',
        follow: 'Followed you',
        reply: 'Replied to your post',
        empty: 'Nothing to show',
      },
      FollowingList: {
        empty: 'You are not following anyone yet',
      },
      Toast: {
        broadcasting: 'Signing and broadcasting transaction',
        wait: 'Please wait a moment...',
        success: '{txLabel} Successful',
        fail: '{txLabel} Failed',
      },
      Settings: {
        enabled: 'Enabled',
        disabled: 'Disabled',
        manageFollows: 'Manage Follows',
        envConfig: 'Environment Config',
        singleSession: 'Single Session',
        defaultAmount: 'Default Amount',
        following: 'Following',
        back: 'Back',
        whatIsIt: 'What is it?',
        singleSessionSummary: 'Single Session creations a local private key through a passkey to sign transactions through the Comsos Authz and Feegrant modules. The settings below let you configure the authorization.',
        createSession: 'Create Session',
        revokeSession: 'Revoke Session',
        defaultAmountSummary: 'You can define a Default Amount of PHOTON to be used for actions (creating post, liking post, following user, etc).\nIf enabled, this amount will be automatically used for transactions when performing actions.',
        defaultAmountWarning: 'Warning: You don\'t have enough balance to use this Default Amount. All actions will fail. Get more PHOTON or adjust this setting.',
      },
      NotFound: {
        title: 'Page Not Found',
        message: 'The page you are looking for does not exist.',
      },
      PostActions: {
        replies: 'reply | replies',
      },
      PostEditorToolbar: {
        insertImageTitle: 'Insert Image URL',
        insertImagePlaceholder: 'https://i.imgur.com/example.jpg',
        insertImageError: 'Provide a direct Imgur image URL (e.g. https://i.imgur.com/example.png)',
        insertVideoTitle: 'Insert Youtube URL',
        insertVideoPlaceholder: 'https://www.youtube.com/watch?v=example',
        insertVideoError: 'Provide a valid Youtube video URL',
        insertButton: 'Insert',
      },
      PostMediaThumbnail: {
        multipleImagesWarning: 'Multiple images detected. Only the first image will be shown.',
        invalidFormatWarning: 'Image URL must end with a valid extension (.gif, .jpg, .png).',
        untrustedDomainWarning: 'Only Imgur images are supported.',
      },
      About: {
        privacyPolicy: 'Privacy Policy',
        termsAndConditions: 'Terms & Conditions',
        docs: 'Documentation',
        heroTagline: 'Open messaging protocol',
        heroSubheading: 'Simple. Durable. Extensible.',
        whatTitle: 'What is Dither',
        whatDesc: 'Read-optimized, event-sourced messaging protocol. Indexes blockchain memos and exposes state via API.',
        whatProtocol: 'Protocol first',
        whatProtocolDesc: 'Run your own service, build your own client, or extend the protocol.',
        whatMinimal: 'Minimal by design',
        whatMinimalDesc: 'Simple protocol that stays out of the way. Communities define their own norms.',
        whatPermanent: 'Onchain posts',
        whatPermanentDesc: 'Posts are stored permanently onchain. Public and verifiable.',
        howTitle: 'How it works',
        howDesc: 'Connect your wallet and start posting. Posts are indexed from the blockchain and appear in your feed.',
        howWeb: 'Web',
        howWebDesc: 'Lightweight frontend for posting and browsing.',
        howTelegram: 'Telegram',
        howTelegramDesc: 'Use Dither from Telegram.',
        howCli: 'CLI',
        howCliDesc: 'Post directly via CLI or build custom clients.',
        faqTitle: 'FAQ',
        faqCrypto: 'Do I need crypto?',
        faqCryptoAnswer: 'You need a wallet. You can post with PHOTON tokens or enable free posting to have fees covered.',
        faqDelete: 'Can I delete posts?',
        faqDeleteAnswer: 'Posts are permanent onchain. Visibility can be controlled in clients.',
        faqCost: 'How much does it cost?',
        faqCostAnswer: 'Minimum 0.000001 PHOTON per post.',
        developersTitle: 'Developers',
        developersDesc: 'Dither works through blockchain memos. Send a bank transfer with a memo like `dither.Post("message")` to the protocol address. The service indexes these memos and reconstructs state.',
        developersApi: 'API',
        developersGithub: 'GitHub',
      },
      Authz: {
        title: 'Authz',
        checkingStatus: 'Checking authorization status...',
        activeGrant: 'Active Authorization',
        activeBanner: 'You have granted authorization to the application',
        grantButton: 'Grant Authorization',
        revokeButton: 'Revoke Authorization',
        granting: 'Granting authorization...',
        revoking: 'Revoking authorization...',
        grantSuccess: 'Authorization granted successfully!',
        grantFailed: 'Failed to grant authorization',
        revokeSuccess: 'Authorization revoked successfully!',
        revokeFailed: 'Failed to revoke authorization',
        summary: 'Authz is a Cosmos SDK module that allows you to grant permission to another address to execute specific actions on your behalf. By granting authorization, you allow the application to send bank transfers with a spending limit of 1 PHOTON to the community wallet only. The grant expires automatically after 1 year.',
      },
    },
    feedbacks: {
      copied: 'Copied to clipboard',
    },
    placeholders: {
      search: 'Type to search',
      post: 'What\'s up?',
      reply: 'Your reply',
    },
  },
};
