export const messages = {
  en: {
    components: {
      ErrorBox: {
        title: 'Error',
        message: 'Something went wrong...',
        cta: 'Please refresh',
      },
      WalletConnect: {
        button: 'Connect Wallet',
        cta: 'Connect Wallet',
        ctaAddress: 'Connect Address',
        balance: 'Balance',
        cancel: 'Cancel',
        back: 'Go back',
        disconnect: 'Disconnect Wallet',
        connecting: 'Connecting Wallet',
        wait: 'Please wait...',
        trouble: 'Troubleshooting',
        slow: 'The connection seems to be slow...',
        retry: 'Try again',
        failed: 'Connection Failed',
        failedSub: 'Was not able to connect to your wallet',
        publicAddressDisclaimer:
                    '* Connecting public address doesn\'t connect to your wallet and is used only for CLI command generation.',
        recommendedWallet: 'We recommend connecting with address only',
        otherWallet: 'Make sure you have a wallet browser extension enabled.',
        enterAddress: 'Enter your wallet address',
        addressPlaceholder: 'e.g. atone1ad453f23bc2d...',
        singleClickDisable: 'Single-Click Disable',
        singleClickEnable: 'Single-Click Enable',
      },
      Wallet: {
        popupSign:
                    'Check your wallet extension to sign the transaction, after submitting the transaction please wait a moment.',
        broadcastSuccess: 'Successfully Broadcasted',
      },
      Button: {
        submit: 'Submit',
        close: 'Close',
        showMore: 'Show more',
        copyLink: 'Copy link',
        follow: 'Follow',
        unfollow: 'Unfollow',
        newPost: 'New post',
        reply: 'Reply',
        closeReply: 'Close Reply',
        createReply: 'Create Reply',
        mintscan: 'See on Mintscan',
        pingpub: 'See on Ping.pub',
        showImage: 'Show image',
        hideImage: 'Hide image',
        viewOnExplorer: 'View on explorer',
        tip: 'Tip',
        adjustDefaultAmount: 'Adjust Default Amount',
      },
      InputPhoton: {
        notEnough: 'Not enough balance',
        placeholder: 'Type amount',
        remaining: 'remaining',
      },
      PopupTitles: {
        likePost: 'Like Post',
        dislikePost: 'Dislike Post',
        newPost: 'New Post',
        reply: 'Reply to Post',
        flagPost: 'Flag Post',
        follow: 'Follow User',
        unfollow: 'Unfollow User',
        tipUser: 'Tip User',
        invalidDefaultAmount: 'Not enough balance',
      },
      PopupDescriptions: {
        flagPost: 'Flagging a post allows our moderation team to take a look and hide it if it violates community guidelines.',
        invalidDefaultAmount: 'You have set a Default Amount and you don\'t have enough balance.\nPlease adjust your Default Amount.',
      },
      Tabs: {
        feed: 'Global Feed',
        following: 'Following',
        posts: 'Posts',
        myPosts: 'My Posts',
        replies: 'Replies',
        myReplies: 'My Replies',
      },
      Headings: {
        profile: 'Profile',
        myProfile: 'My Profile',
        notifications: 'Notifications',
        settings: 'Settings',
        manageFollows: 'Manage Following',
        envConfig: 'Environment Config',
        authz: 'Authz',
        post: 'Post',
        explore: 'Explore',
        about: 'About',
      },
      SearchInput: {
        noResults: 'No results found',
        failedToSearch: 'Failed to search',
      },
      Filter: {
        posts: 'Filter posts by PHOTON',
        amount: 'Amount',
      },
      PostsList: {
        empty: 'No Posts Available',
      },
      PostView: {
        invalidDefaultAmount: 'You can\'t reply to this post because you have set a Default Amount and you don\'t have enough balance.\nPlease adjust your Default Amount.',
      },
      RepliesGroupsList: {
        empty: 'No Replies Available',
      },
      Notifications: {
        like: 'Liked your post',
        dislike: 'Disliked your post',
        flag: 'Redflagged your post',
        follow: 'Followed you',
        reply: 'Replied to your post',
        empty: 'Nothing to show',
      },
      FollowingList: {
        empty: 'You are not following anyone yet',
      },
      Toast: {
        broadcasting: 'Signing and broadcasting transaction',
        wait: 'Please wait a moment...',
        success: '{txLabel} Successful',
        fail: '{txLabel} Failed',
      },
      Settings: {
        enabled: 'Enabled',
        disabled: 'Disabled',
        manageFollows: 'Manage Follows',
        envConfig: 'Environment Config',
        singleSession: 'Single Session',
        defaultAmount: 'Default Amount',
        following: 'Following',
        back: 'Back',
        whatIsIt: 'What is it?',
        singleSessionSummary: 'Single Session creations a local private key through a passkey to sign transactions through the Comsos Authz and Feegrant modules. The settings below let you configure the authorization.',
        createSession: 'Create Session',
        revokeSession: 'Revoke Session',
        defaultAmountSummary: 'You can define a Default Amount of PHOTON to be used for actions (creating post, liking post, following user, etc).\nIf enabled, this amount will be automatically used for transactions when performing actions.',
        defaultAmountWarning: 'Warning: You don\'t have enough balance to use this Default Amount. All actions will fail. Get more PHOTON or adjust this setting.',
      },
      NotFound: {
        title: 'Page Not Found',
        message: 'The page you are looking for does not exist.',
      },
      PostActions: {
        replies: 'reply | replies',
      },
      About: {
        privacyPolicy: 'Privacy Policy',
        termsAndConditions: 'Terms & Conditions',
        docs: 'Documentation',
      },
      Authz: {
        title: 'Authz',
        checkingStatus: 'Checking authorization status...',
        activeGrant: 'Active Authorization',
        activeBanner: 'You have granted authorization to the application',
        grantButton: 'Grant Authorization',
        revokeButton: 'Revoke Authorization',
        granting: 'Granting authorization...',
        revoking: 'Revoking authorization...',
        grantSuccess: 'Authorization granted successfully!',
        grantFailed: 'Failed to grant authorization',
        revokeSuccess: 'Authorization revoked successfully!',
        revokeFailed: 'Failed to revoke authorization',
        summary: 'Authz is a Cosmos SDK module that allows you to grant permission to another address to execute specific actions on your behalf. By granting authorization, you allow the application to send bank transfers with a spending limit of 1 PHOTON to the community wallet only. The grant expires automatically after 1 year.',
      },
    },
    feedbacks: {
      copied: 'Copied to clipboard',
    },
    placeholders: {
      search: 'Type to search',
      post: 'What\'s up?',
      reply: 'Your reply',
    },
  },
};
