export const messages = {
    en: {
        components: {
            ErrorBox: {
                title: 'Error',
                message: 'Something went wrong...',
                cta: 'Please refresh',
            },
            WalletConnect: {
                button: 'Connect Wallet',
                cta: 'Connect Wallet',
                ctaAddress: 'Connect Address',
                balance: 'Balance',
                cancel: 'Cancel',
                back: 'Go back',
                disconnect: 'Disconnect wallet',
                connecting: 'Connecting wallet',
                wait: 'Please wait...',
                trouble: 'Troubleshooting',
                slow: 'The connection seems to be slow...',
                retry: 'Try again',
                failed: 'Connection Failed',
                failedSub: 'Was not able to connect to your wallet',
                publicAddressDisclaimer:
                    '* Connecting public address doesn\'t connect to your wallet and is used only for CLI command generation.',
                recommendedWallet: 'We recommend connecting with address only',
                otherWallet: 'Make sure you have a wallet browser extension enabled.',
                enterAddress: 'Enter your wallet address',
                addressPlaceholder: 'e.g. atone1ad453f23bc2d...',
            },
            Wallet: {
                popupSign:
                    'Check your wallet extension to sign the transaction, after submitting the transaction please wait a moment.',
                broadcastSuccess: 'Successfully Broadcasted',
            },
            Button: {
                submit: 'Submit',
                close: 'Close',
                showMore: 'Show more',
                copyLink: 'Copy link',
                follow: 'Follow',
                unfollow: 'Unfollow',
                newPost: 'New post',
                reply: 'Reply',
                mintscan: 'See on Mintscan',
                pingpub: 'See on Ping.pub',
                showImage: 'Show image',
                hideImage: 'Hide image',
                viewOnExplorer: 'View on explorer',
                tip: 'Tip',
            },
            InputPhoton: {
                notEnough: 'Not enough balance',
                placeholder: 'Type amount',
                available: 'available',
            },
            PopupTitles: {
                likePost: 'Like Post',
                dislikePost: 'Dislike Post',
                newPost: 'New Post',
                reply: 'Reply to Post',
                flagPost: 'Flag Post',
                follow: 'Follow User',
                unfollow: 'Unfollow User',
                tipUser: 'Tip User',
            },
            PopupDescriptions: {
                flagPost: 'Flagging a post allows our moderation team to take a look and hide it if it violates community guidelines.',
            },
            Tabs: {
                feed: 'Global Feed',
                following: 'Following',
                posts: 'Posts',
                myPosts: 'My Posts',
                replies: 'Replies',
                myReplies: 'My Replies',
            },
            Headings: {
                profile: 'Profile',
                myProfile: 'My Profile',
                notifications: 'Notifications',
                settings: 'Settings',
                manageFollows: 'Manage Following',
                envConfig: 'Environment Config',
                post: 'Post',
                explore: 'Explore',
            },
            SearchInput: {
                noResults: 'No results found',
                failedToSearch: 'Failed to search',
            },
            Filter: {
                posts: 'Filter posts by PHOTON',
                amount: 'Amount',
            },
            PostsList: {
                empty: 'No Posts Available',
            },
            RepliesGroupsList: {
                empty: 'No Replies Available',
            },
            Notifications: {
                like: 'Liked your post',
                dislike: 'Disliked your post',
                flag: 'Redflagged your post',
                follow: 'Followed you',
                reply: 'Replied to your post',
                empty: 'Nothing to show',
            },
            FollowingList: {
                empty: 'You are not following anyone yet',
            },
            Toast: {
                broadcasting: 'Signing and broadcasting transaction',
                wait: 'Please wait a moment...',
                success: '{txLabel} Successful',
                fail: '{txLabel} Failed',
            },
            NotFound: {
                title: 'Page Not Found',
                message: 'The page you are looking for does not exist.',
            },
        },
        feedbacks: {
            copied: 'Copied to clipboard',
        },
        placeholders: {
            search: 'Type to search',
            post: 'What\'s up?',
            reply: 'Your reply',
        },
    },
};
