# fly.toml app configuration file generated for dither-testnet-reader-main on 2025-06-05T15:58:33-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dither-testnet-reader-main'
primary_region = 'iad'

[build]

# non-secret environment variables
# AUTH is also required but is set in the secrets on fly.io
[env]
BATCH_SIZE = "500"
MEMO_PREFIX = "dither."
START_BLOCK = "1979480"
RECEIVER = "atone1uq6zjslvsa29cy6uu75y8txnl52mw06j6fzlep"
API_ROOT = "http://dither-testnet-api-main.internal:3000/v1"
API_URLS = "https://atomone-testnet-1-api.allinbits.services"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
