app = 'dither-mainnet-reader-main'
primary_region = 'iad'

[build]
[env]
BATCH_SIZE = "500"
MEMO_PREFIX = "dither."
START_BLOCK = "5114165"
RECEIVER = "atone1uq6zjslvsa29cy6uu75y8txnl52mw06j6fzlep"
API_ROOT = "http://dither-mainnet-api-main.internal:3000/v1"
API_URLS = "https://atomone-api.allinbits.services"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
